# Project Configuration
project:
  name: "multi-task-perception"
  version: "1.0.0"
  description: "Multi-task perception system for autonomous vehicles"

# Hardware Configuration
hardware:
  device: "cpu"  # or "cuda"
  num_workers: 4
  pin_memory: true
  mixed_precision: true

# Model Configuration
model:
  backbone:
    name: "resnet50"
    pretrained: true
    freeze_bn: true
  input_size: [512, 512]
  num_classes:
    semantic: 4  # road, lane, vehicle, pedestrian
    detection: 3  # vehicle, pedestrian, traffic_light
    classification: 2  # stain, no_stain
  fpn_channels: 256
  detection:
    num_anchors: 9
    anchor_sizes: [32, 64, 128, 256, 512]
    anchor_ratios: [0.5, 1.0, 2.0]

# Training Configuration
training:
  batch_size: 16
  epochs: 100
  optimizer:
    name: "adamw"
    lr: 0.0001
    weight_decay: 0.01
  scheduler:
    name: "cosine"
    warmup_epochs: 5
    min_lr: 0.00001
  loss:
    uncertainty_weighting: true
    semantic_weight: 1.0
    detection_weight: 1.0
    classification_weight: 1.0
    depth_weight: 1.0

# Data Configuration
data:
  train_path: "data/train"
  val_path: "data/val"
  test_path: "data/test"
  augmentation:
    enabled: true
    horizontal_flip: 0.5
    vertical_flip: 0.0
    rotation: 15
    brightness_contrast: 0.2
    blur: 0.1

# Logging Configuration
logging:
  level: "INFO"
  log_dir: "logs"
  wandb:
    enabled: true
    project: "multi-task-perception"
    entity: "usamahz"
  tensorboard:
    enabled: true
    log_dir: "logs/tensorboard"
  checkpoint:
    save_dir: "checkpoints"
    save_freq: 5
    keep_last: 5

# Deployment Configuration
deployment:
  onnx:
    enabled: true
    opset_version: 11
    dynamic_axes: true
  quantization:
    enabled: true
    dtype: "int8"
  export_dir: "exported_models"
